# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: verifier-policy
description: "Verifiable Credentials Adapters: the verifier-policy service."
type: application
version: 0.1.0
appVersion: "0.1.0"
