# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: verifier-combined
description: "Verifiable Credentials Adapters: the verifier-combined service."
type: application
version: 0.1.0
appVersion: "0.1.0"
