# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: wallet-portal
description: "Verifiable Credentials Adapters: the wallet-portal service."
type: application
version: 0.1.0
appVersion: "0.1.0"
