# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: issued-credentials
description: "Verifiable Credentials Adapters: the issued-credentials service."
type: application
version: 0.1.0
appVersion: "0.1.0"
