#!/usr/bin/env bash
# gen-wallet-values.sh — write the Helm values file carrying walt-wallet's
# token-signing key, generating the key on first use.
#
# WHY THIS EXISTS, AND WHY IT IS SHARED
#
# walt-wallet's chart requires wallet.tokenKey and deliberately has no default.
# The key used to ship AS a chart default, so every deployment that did not
# override it signed wallet tokens with the same RSA key -- and that key is in
# the git history of a public repo. Removing the default was right.
#
# Nothing then generated one for the K8s path. The compose path got
# scripts/gen-demo-pki.sh; this one got nothing. So helm_release.waltid failed
# at template render -- in about four seconds, before a single pod was
# scheduled -- on every nightly cluster run from the day the default was
# removed.
#
# It survived thirteen nights because CI's render tier generated a throwaway
# key inline and passed it with --set-string. That proved the chart renders IF
# someone supplies a key, while the thing that actually deploys supplied none.
# The two paths had drifted, and the green check hid the red one.
#
# Hence one script, called by both. If it breaks, both break, which is the
# property that was missing.
#
# CONTRACT
#
# Idempotent: an existing file is left alone, so re-running `up` never rotates
# the key under a live cluster. Delete the file to issue a fresh one. The
# output is gitignored and written 0600. Prints the path on stdout so a caller
# can use it directly.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
K8S_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(cd "$K8S_DIR/../.." && pwd)"

gen_wallet_values() {
  local out="${1:-$K8S_DIR/config/wallet/values.generated.yaml}"

  if [[ -s "$out" ]]; then
    printf '%s\n' "$out"
    return 0
  fi

  command -v openssl >/dev/null || {
    echo "gen-wallet-values: openssl not found — cannot generate the wallet signing key" >&2
    return 1
  }
  command -v python3 >/dev/null || {
    echo "gen-wallet-values: python3 not found — cannot generate the wallet signing key" >&2
    return 1
  }

  local jwk
  jwk="$(openssl genrsa 2048 2>/dev/null | python3 "$ROOT_DIR/scripts/pem-to-jwk.py")" || true
  [[ -n "$jwk" ]] || {
    echo "gen-wallet-values: JWK generation failed" >&2
    return 1
  }

  mkdir -p "$(dirname "$out")"
  # A single-quoted YAML scalar. The JWK is JSON -- double quotes throughout --
  # and base64url contains no single quote, so nothing needs escaping. The
  # chart wraps this value in double quotes, which reproduces exactly the HOCON
  # shape walt.id read back when the key was still committed.
  {
    echo "# Generated by deploy/k8s/scripts/gen-wallet-values.sh."
    echo "# NEVER COMMIT: this is a token-signing key."
    echo "# Delete this file to issue a fresh one on the next run."
    echo "walt-wallet:"
    echo "  wallet:"
    printf "    tokenKey: '%s'\n" "$jwk"
  } > "$out"
  chmod 600 "$out"
  printf '%s\n' "$out"
}

# Allow running standalone: ./deploy/k8s/scripts/gen-wallet-values.sh [path]
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  gen_wallet_values "${1:-}"
fi
