// SPDX-License-Identifier: Apache-2.0

package msg

// en is the English catalogue. Keep every value inside the STE rules that
// msg_test.go checks: short sentences, active voice, approved words.
var en = map[string]string{
	// Layout and shell.
	"layout.skip.label":         "Skip to content",
	"layout.theme.label":        "Theme",
	"layout.theme.system.label": "System",
	"layout.theme.light.label":  "Light",
	"layout.theme.dark.label":   "Dark",
	"shell.main_nav.label":      "Main",
	"shell.stack_nav.label":     "Stack",
	"shell.side_nav.label":      "Portal",
	"shell.menu.label":          "Menu",
	"shell.sign_out.label":      "Sign out",
	"shell.starting.label":      "Starting",
	"shell.signed_in_as.label":  "Signed in as {1}",

	// Words that many pages share.
	"common.open.label":            "Open",
	"common.close.label":           "Close",
	"common.back.label":            "Back",
	"common.continue.label":        "Continue",
	"common.cancel.label":          "Cancel",
	"common.save.label":            "Save",
	"common.delete.label":          "Delete",
	"common.search.label":          "Search",
	"common.change.label":          "Change",
	"common.done.label":            "Done",
	"common.current.label":         "Current",
	"common.locked.label":          "Locked",
	"common.to_do.label":           "To do",
	"common.live.label":            "Live",
	"common.no_rows.label":         "No rows",
	"common.help.label":            "Help",
	"common.overview.label":        "Overview",
	"common.notifications.label":   "Notifications",
	"common.recent_activity.label": "Recent activity",
	"common.when.label":            "When",
	"common.event.label":           "Event",
	"common.detail.label":          "Detail",
	"common.status.label":          "Status",
	"common.name.label":            "Name",
	"common.version.label":         "Version",
	"common.updated.label":         "Updated {1}",
	"common.github.label":          "GitHub",
	"common.documentation.label":   "Documentation",
	"common.not_found":             "This page does not exist.",
	"common.render_failed":         "The page did not render. Try again.",
	"common.session_expired":       "Your session ended. Sign in again to continue.",

	// Roles.
	"role.admin.label":    "Admin",
	"role.issuer.label":   "Issuer",
	"role.holder.label":   "Holder",
	"role.verifier.label": "Verifier",

	// Landing page.
	"landing.title.label":             "VCA",
	"landing.hero.label":              "Verifiable Credentials Adapter",
	"landing.hero.title":              "One front door to open credential infrastructure.",
	"landing.hero.lead":               "VCA lets a government or an institution issue, hold and check digital credentials on open source stacks. One interface drives every stack.",
	"landing.hero.start.label":        "Start with VCA",
	"landing.hero.primer":             "New to credentials? Read the primer.",
	"landing.nav.how.label":           "How it works",
	"landing.nav.stacks.label":        "Stacks",
	"landing.nav.docs.label":          "Docs",
	"landing.nav.start.label":         "Start",
	"landing.how.title":               "Three ideas, two minutes.",
	"landing.how.lead":                "Enough to use VCA. Links go deeper.",
	"landing.how.dpg.label":           "A Digital Public Good",
	"landing.how.dpg.text":            "Open source software that governments can run, inspect and change. VCA drives the DPGs that issue and check credentials, so you can try each without learning each.",
	"landing.how.dpg.link.label":      "The DPG Standard",
	"landing.how.vc.label":            "A verifiable credential",
	"landing.how.vc.text":             "A digital document, like a licence or a degree, that an organisation signs and a person keeps in a wallet. Anyone who sees it can check who signed it and that nothing changed.",
	"landing.how.vc.link.label":       "W3C data model",
	"landing.how.triangle.label":      "The triangle of trust",
	"landing.how.triangle.text":       "An issuer signs, a holder keeps and presents, a verifier checks. VCA adds a trust registry and trust lists, so a verifier knows which issuers to accept.",
	"landing.how.triangle.alt":        "Issuer, holder and verifier, with the trust registry between them.",
	"landing.stacks.label":            "Stacks on this deployment",
	"landing.stacks.lead":             "Only running services appear. A role that does not run never shows as available.",
	"landing.stacks.pinned.label":     "Pinned {1}",
	"landing.stacks.components.label": "Components",
	"landing.stacks.none":             "No stack runs yet. Start a pair with the vca command, then reload this page.",
	"landing.cta.title":               "Pick a role. Walk one flow end to end.",
	"landing.cta.lead":                "Issue a credential, hold it in a wallet, check it. Each step hands you to the next.",
	"landing.cta.one_role.title":      "One role is live. Start there.",
	"landing.cta.one_role.lead":       "The role picker steps aside when one role runs.",
	"landing.footer":                  "Centre for Digital Public Infrastructure, Apache-2.0.",
	"landing.one_role.label":          "One role",
	"landing.one_role.text":           "This deployment runs the {1} role on {2}. Other roles appear when an admin deploys them.",
	"landing.one_role.continue.label": "Continue as {1}",
	"landing.none.label":              "No role yet",
	"landing.how.triangle.link.label": "Roles in the ecosystem",
	"landing.stacks.meta.label":       "VCA {1}",
	"landing.stacks.component.label":  "pinned {1}",
	"landing.stacks.roles.label":      "Roles",
	"landing.triangle.issues.label":   "issues",
	"landing.triangle.presents.label": "presents",
	"landing.triangle.trusts.label":   "trusts",
	"landing.triangle.registry.label": "Trust registry",

	// Role picker.
	"roles.title":              "How do you want to proceed?",
	"roles.lead":               "Each role has its own sign in and its own portal. You can come back and try another role at any time. The cards reflect what runs on this deployment.",
	"roles.issuer.label":       "Proceed as issuer",
	"roles.issuer.text":        "Register your organisation, define what you issue, then issue credentials one at a time or in bulk.",
	"roles.holder.label":       "Proceed as holder",
	"roles.holder.text":        "Discover what issuers offer, claim credentials into a wallet and present them when asked.",
	"roles.verifier.label":     "Proceed as verifier",
	"roles.verifier.text":      "Build a presentation request, receive a presentation, check signature, trust and status.",
	"roles.admin.label":        "Proceed as admin",
	"roles.admin.title":        "Operating this deployment?",
	"roles.admin.text":         "Manage trust lists and registries, login providers, tenants, API keys and the audit log.",
	"roles.available_on.label": "Available on {1}",
	"roles.one_role":           "This deployment runs one role, so you go straight to it.",
	"roles.other_admins.label": "Other admin portals",
	"roles.none.title":         "No role runs yet.",
	"roles.none.text":          "Start a pair with the vca command, then come back.",

	// Role intro pages.
	"intro.all_roles.label":        "All roles",
	"intro.what.label":             "What you can do",
	"intro.signin.label":           "Sign in to continue",
	"intro.signin.through":         "This deployment signs {1} in through {2}.",
	"intro.signin.realm":           "This deployment signs {1} in through {2} in the realm {3}.",
	"intro.signin.register":        "You can register if you have no account.",
	"intro.signin.lead":            "Each stack signs you in on its own pair. You can register if you have no account.",
	"intro.signin.continue.label":  "Continue to sign in",
	"intro.signin.stack.label":     "Continue on {1}",
	"intro.steps.lead":             "{1} steps on this deployment. Each one hands you to the next.",
	"intro.not_live":               "This deployment runs no {1} yet. Pick another role.",
	"intro.issuer.step3.oid4vci":   "Deliver by OID4VCI.",
	"intro.issuer.step3.pdf":       "Print a QR on a PDF for holders without a wallet.",
	"intro.verifier.step2.dcql":    "Compose a DCQL query.",
	"intro.verifier.step2.pe":      "Older wallets take a DIF Presentation Exchange query.",
	"intro.admin.trust.label":      "Set who to trust",
	"intro.admin.trust.text":       "Add issuers to the trust list. A verifier rejects unknown issuers.",
	"intro.admin.registries.label": "Connect trust registries",
	"intro.admin.registries.text":  "Publish your registry and federate with external ones.",
	"intro.admin.providers.label":  "Set up sign in",
	"intro.admin.providers.text":   "One realm per role by default. Add another OIDC provider when you need it.",
	"intro.admin.tenants.label":    "Add tenants",
	"intro.admin.tenants.text":     "Separate organisations on a stack that supports tenancy.",
	"intro.admin.keys.label":       "Keys and audit",
	"intro.admin.keys.text":        "Issue API keys for services and read the audit log.",
	"number.1.label":               "One",
	"number.2.label":               "Two",
	"number.3.label":               "Three",
	"number.4.label":               "Four",
	"number.5.label":               "Five",
	"number.6.label":               "Six",
	"intro.issuer.title":           "Issue credentials, step by step.",
	"intro.issuer.step1.label":     "Identify your organisation",
	"intro.issuer.step1.text":      "Register keys and metadata with the trust registry, in one click or with what you already have.",
	"intro.issuer.step2.label":     "Define what you issue",
	"intro.issuer.step2.text":      "Publish a schema, or build one in the schema builder. Version, extend and retire it later.",
	"intro.issuer.step3.label":     "Issue",
	"intro.issuer.step3.text":      "One credential typed by hand, or thousands from a data source.",
	"intro.issuer.step4.label":     "Manage what you issued",
	"intro.issuer.step4.text":      "Search issued credentials, review their data, suspend or revoke.",
	"intro.holder.title":           "Hold and present credentials, step by step.",
	"intro.holder.step1.label":     "Discover offers",
	"intro.holder.step1.text":      "Find what the issuers on this deployment offer.",
	"intro.holder.step2.label":     "Claim a credential",
	"intro.holder.step2.text":      "Scan a QR or follow a link. The credential lands in your wallet.",
	"intro.holder.step3.label":     "Present it",
	"intro.holder.step3.text":      "Answer a verifier's request with the claims it asks for, and nothing more.",
	"intro.holder.step4.label":     "Review what you hold",
	"intro.holder.step4.text":      "See every credential, its issuer and its status.",
	"intro.verifier.title":         "Check credentials, step by step.",
	"intro.verifier.step1.label":   "Discover schemas",
	"intro.verifier.step1.text":    "Find the credential types you can ask for.",
	"intro.verifier.step2.label":   "Build a request",
	"intro.verifier.step2.text":    "Ask for the claims you need.",
	"intro.verifier.step3.label":   "Receive a presentation",
	"intro.verifier.step3.text":    "Show a QR, paste a link or upload a document.",
	"intro.verifier.step4.label":   "Check the result",
	"intro.verifier.step4.text":    "Signature, trust and status, online or from the cache within your window.",
	"intro.admin.title":            "Run the deployment, step by step.",
	"intro.admin.step1.label":      "Sign in as admin",
	"intro.admin.step1.text":       "The first admin registers, then turns self registration off.",
	"intro.admin.step2.label":      "Set who to trust",
	"intro.admin.step2.text":       "Add issuers to the trust list and connect trust registries.",
	"intro.admin.step3.label":      "Set up sign in",
	"intro.admin.step3.text":       "One realm per role by default. Add another OIDC provider when you need it.",
	"intro.admin.step4.label":      "Manage the rest",
	"intro.admin.step4.text":       "Tenants, API keys, the audit log and notifications.",

	// Sign in chooser (ADR-035).
	"signin.title.label":               "Sign in",
	"signin.description":               "Sign in uses OpenID Connect only. VCA stores no password.",
	"signin.issuer.title":              "Sign in as an issuer.",
	"signin.holder.title":              "Sign in as a holder.",
	"signin.verifier.title":            "Sign in as a verifier.",
	"signin.admin.title":               "Sign in as an admin.",
	"signin.issuer.return":             "You return to the issuer portal after sign in.",
	"signin.holder.return":             "You return to your wallet after sign in.",
	"signin.verifier.return":           "You return to the verifier portal after sign in.",
	"signin.admin.return":              "You return to the admin portal after sign in.",
	"signin.providers.text":            "The admin sets the login providers, so a deployment can use Keycloak, WSO2 Identity Server or its own OIDC provider.",
	"signin.back.label":                "Choose another role",
	"signin.continue.label":            "Continue with",
	"signin.none":                      "This deployment has no login provider yet. Ask the admin to add one.",
	"signin.admin.none":                "This deployment has no login provider yet. Run vca admin onboard to add one.",
	"signin.register.label":            "Register a new account",
	"signin.register.with.label":       "Register with {1}",
	"signin.or.label":                  "or",
	"signin.note":                      "VCA is not tied to Keycloak. Any OIDC provider the admin adds appears here.",
	"signin.admin.callout.label":       "First admin after deployment?",
	"signin.admin.callout":             "Paste the bootstrap token, then register or sign in. Then turn off self registration in the realm settings.",
	"signin.admin.bootstrap.label":     "First super admin",
	"signin.admin.bootstrap.text":      "Paste the bootstrap token that the service printed at its first start. The token binds your identity to the super admin role once.",
	"signin.admin.provider.label":      "Provider id",
	"signin.admin.provider.hint":       "Leave the field empty when the deployment has one provider.",
	"signin.admin.token.label":         "Bootstrap token",
	"signin.admin.bind.label":          "Sign in and bind",
	"signin.admin.register_bind.label": "Register and bind",
	"role.issuer.plural.label":         "issuers",
	"role.holder.plural.label":         "holders",
	"role.verifier.plural.label":       "verifiers",
	"role.admin.plural.label":          "admins",

	// Admin portal.
	"admin.nav.trust_lists.label":               "Trust lists",
	"admin.nav.trust_registries.label":          "Trust registries",
	"admin.nav.providers.label":                 "Login providers",
	"admin.nav.tenants.label":                   "Tenants",
	"admin.nav.api_keys.label":                  "API keys",
	"admin.nav.audit.label":                     "Audit log",
	"admin.nav.console.label":                   "Identity console",
	"admin.nav.section.trust.label":             "Trust",
	"admin.nav.section.access.label":            "Access",
	"admin.nav.section.records.label":           "Records",
	"admin.overview.lead":                       "What this deployment trusts, who can sign in, and what changed.",
	"admin.stat.trust_list.label":               "Trust list",
	"admin.stat.trust_list.value.label":         "{1} trusted issuers",
	"admin.stat.trust_list.one.label":           "1 trusted issuer",
	"admin.stat.trust_list.none_registry.label": "No trust registry",
	"admin.stat.trust_list.text":                "Issuers a verifier on this deployment accepts.",
	"admin.stat.registries.value.label":         "Local registry",
	"admin.stat.registries.text":                "Add an external registry to federate.",
	"admin.stat.providers.value.label":          "{1} providers",
	"admin.stat.providers.one.label":            "1 provider",
	"admin.stat.providers.realm.value.label":    "{1} realms",
	"admin.stat.providers.realm.one.label":      "1 realm",
	"admin.stat.providers.text":                 "One realm per role. Add another OIDC provider.",
	"admin.stat.tenants.value.label":            "{1} tenants",
	"admin.stat.tenants.one.label":              "1 tenant",
	"admin.stat.tenants.text":                   "Add tenants where a stack supports them.",
	"admin.stat.api_keys.value.label":           "{1} keys",
	"admin.stat.api_keys.one.label":             "1 key",
	"admin.stat.api_keys.none.label":            "No keys yet",
	"admin.stat.api_keys.text":                  "Keys for services that call VCA without a user.",
	"admin.stat.audit.value.label":              "{1} events today",
	"admin.stat.audit.one.label":                "1 event today",
	"admin.stat.audit.text":                     "Sign ins, trust changes, issuance and verification.",
	"admin.checklist.title.label":               "First run checklist",
	"admin.checklist.note":                      "Steps stay until done.",
	"admin.checklist.register.label":            "Register the first admin",
	"admin.checklist.register.text":             "Register the first admin.",
	"admin.checklist.register.detail":           "Bound through {1}.",
	"admin.checklist.self_reg.text":             "Turn off self registration for admins.",
	"admin.checklist.self_reg.detail":           "Run vca dpg realm with the role admin and the registration off. Or set the admin provider register action to none.",
	"admin.checklist.password.text":             "Change the identity provider admin password.",
	"admin.checklist.password.detail":           "The deploy uses a default that must not stay.",
	"admin.checklist.trust.text":                "Add at least one issuer to the trust list.",
	"admin.checklist.trust.detail":              "A verifier rejects unknown issuers.",
	"admin.checklist.providers.text":            "Set the login provider for each role.",
	"admin.checklist.providers.detail":          "Defaults: one realm per role.",
	"admin.checklist.providers.missing":         "No provider yet for {1}.",
	"admin.notifications.lead":                  "Where the events of this deployment go, and who sends them.",

	// Admin tenants (owner spec AD5, ADR-037).
	"admin.tenants.lead":                      "A tenant is one organisation that uses this deployment. A stack with multi tenancy gives it a space of its own.",
	"admin.tenants.caption.label":             "Tenants, {1} found",
	"admin.tenants.empty":                     "No tenant exists. Create the first tenant below.",
	"admin.tenants.column.name.label":         "Tenant",
	"admin.tenants.column.stacks.label":       "Stacks",
	"admin.tenants.column.state.label":        "State",
	"admin.tenants.column.created.label":      "Created",
	"admin.tenants.column.actions.label":      "Actions",
	"admin.tenants.column.stack.label":        "Stack",
	"admin.tenants.column.stack_tenant.label": "Stack tenant",
	"admin.tenants.column.dids.label":         "DIDs",
	"admin.tenants.state.active.label":        "Active",
	"admin.tenants.state.suspended.label":     "Suspended",
	"admin.tenants.vca_only.label":            "VCA only",
	"admin.tenants.new.label":                 "New tenant",
	"admin.tenants.new.text":                  "The tenant owns API keys and audit records in VCA.",
	"admin.tenants.new.stacks.text":           "The tenant owns API keys in VCA. Choose the stacks that create a tenant of their own too.",
	"admin.tenants.display_name.label":        "Display name",
	"admin.tenants.stacks.label":              "Also create on stacks",
	"admin.tenants.stacks.hint":               "The list shows the running stacks with multi tenancy. No box keeps the tenant in VCA only.",
	"admin.tenants.stack.label":               "Stack",
	"admin.tenants.stack.text":                "The stack keeps tenants apart.",
	"admin.tenants.agent.label":               "Agent",
	"admin.tenants.agent.default.label":       "Stack default",
	"admin.tenants.agent.default.text":        "The stack picks the agent.",
	"admin.tenants.agent.shared.label":        "Shared agent",
	"admin.tenants.agent.shared.text":         "The tenant shares one agent with other tenants.",
	"admin.tenants.agent.dedicated.label":     "Dedicated agent",
	"admin.tenants.agent.dedicated.text":      "The tenant gets an agent of its own.",
	"admin.tenants.create.label":              "Create tenant",
	"admin.tenants.tenant.label":              "Tenant",
	"admin.tenants.detail.lead":               "The tenant in VCA and its tenant on each stack.",
	"admin.tenants.details.label":             "Tenant details",
	"admin.tenants.id.label":                  "Tenant id",
	"admin.tenants.delete.label":              "Delete tenant",
	"admin.tenants.back.label":                "All tenants",
	"admin.tenants.on_stacks.label":           "On stacks",
	"admin.tenants.on_stacks.lead":            "Each stack keeps its own tenant record with its DIDs. VCA reads them now.",
	"admin.tenants.bindings.caption.label":    "Stack tenants, {1} found",
	"admin.tenants.bound_at.label":            "Bound {1}",
	"admin.tenants.no_dids.label":             "No DID yet",
	"admin.tenants.binding.ok.label":          "Reachable",
	"admin.tenants.binding.error.label":       "Not reachable",
	"admin.tenants.no_bindings.text":          "The tenant lives in VCA only. Add it to a stack to give it a space there.",
	"admin.tenants.stack.version.label":       "Version {1}",
	"admin.tenants.bind.label":                "Add to stack",
	"admin.tenants.bind.text":                 "The stack creates a tenant with the same name. VCA records the binding.",
	"admin.tenants.unbind.label":              "Remove from stack",
	"admin.tenants.created":                   "You created the tenant.",
	"admin.tenants.deleted":                   "You removed the tenant with its records and its stack tenants.",
	"admin.tenants.bound":                     "The stack holds the tenant now.",
	"admin.tenants.unbound":                   "The stack removed its tenant.",

	// Admin API keys and stack credentials (owner spec AD7, ADR-038).
	"admin.keys.lead":                         "A machine calls VCA with an API key. Each key belongs to one tenant and can end on a date.",
	"admin.keys.stack.lead":                   "A machine calls VCA with an API key. It calls a stack with the client credential of a stack tenant.",
	"admin.keys.vca.label":                    "VCA API keys",
	"admin.keys.vca.lead":                     "The services check these keys. The service keeps only a hash of each secret.",
	"admin.keys.caption.label":                "API keys, {1} found",
	"admin.keys.empty":                        "No API key exists. Create one below.",
	"admin.keys.column.name.label":            "Name",
	"admin.keys.column.prefix.label":          "Prefix",
	"admin.keys.column.tenant.label":          "Tenant",
	"admin.keys.column.roles.label":           "Roles",
	"admin.keys.column.expires.label":         "Expires",
	"admin.keys.column.state.label":           "State",
	"admin.keys.column.actions.label":         "Actions",
	"admin.keys.state.active.label":           "Active",
	"admin.keys.state.expired.label":          "Expired",
	"admin.keys.state.revoked.label":          "Revoked",
	"admin.keys.revoke.label":                 "Revoke",
	"admin.keys.new.label":                    "New API key",
	"admin.keys.new.text":                     "The key acts for its tenant with one role.",
	"admin.keys.display_name.label":           "Name",
	"admin.keys.tenant.hint":                  "The key acts for this tenant only.",
	"admin.keys.role.label":                   "Role",
	"admin.keys.expiry.label":                 "Expiry",
	"admin.keys.expiry.hint":                  "After this time every call with the key fails.",
	"admin.keys.expiry.30.label":              "30 days",
	"admin.keys.expiry.90.label":              "90 days",
	"admin.keys.expiry.365.label":             "One year",
	"admin.keys.expiry.none.label":            "No end date",
	"admin.keys.expiry.never.label":           "No end",
	"admin.keys.create.label":                 "Create key",
	"admin.keys.no_tenant.title":              "Create a tenant first.",
	"admin.keys.no_tenant.text":               "Every API key belongs to one tenant.",
	"admin.keys.secret.label":                 "The new key secret",
	"admin.keys.secret.text":                  "Copy the value now. The service shows it once and keeps only its hash.",
	"admin.keys.secret.value.label":           "Secret",
	"admin.keys.secret.footer":                "Keep the value in a secret manager.",
	"admin.keys.created":                      "You created the API key.",
	"admin.keys.revoked":                      "You revoked the API key. Calls with it fail now.",
	"admin.keys.stack.label":                  "Stack credentials",
	"admin.keys.stack.block.lead":             "Each stack tenant can hold client credentials of its own. The stack checks them, not VCA.",
	"admin.keys.stack.caption.label":          "Stack credentials, {1} found",
	"admin.keys.stack.none":                   "No stack credential exists. Create one below.",
	"admin.keys.stack.column.client_id.label": "Client ID",
	"admin.keys.stack.column.stack.label":     "Stack",
	"admin.keys.stack.column.created.label":   "Created",
	"admin.keys.stack.new.label":              "New stack credential",
	"admin.keys.stack.new.text":               "The stack makes the credential for the tenant you choose.",
	"admin.keys.stack.target.label":           "Tenant on stack",
	"admin.keys.stack.target.value.label":     "{1} on {2}",
	"admin.keys.stack.create.label":           "Create credential",
	"admin.keys.stack.empty.title":            "No tenant sits on a stack with client credentials.",
	"admin.keys.stack.empty.text":             "Add a tenant to such a stack on the tenants page first.",
	"admin.keys.stack.tenants.label":          "Open tenants",
	"admin.keys.stack.secret.label":           "The new stack credential",
	"admin.keys.stack.secret.text":            "Copy both values now. {1} shows the secret once, and VCA keeps no copy.",
	"admin.keys.stack.client_id.label":        "Client ID",
	"admin.keys.stack.client_secret.label":    "Client secret",
	"admin.keys.stack.created":                "The stack created the client credential.",
	"admin.keys.stack.deleted":                "The stack removed the client credential.",
	"admin.keys.stack.fault":                  "VCA could not read {1}.",

	// Admin notifications (owner spec AD9, ADR-040).
	"admin.notifications.delivery.label":         "VCA delivery",
	"admin.notifications.delivery.lead":          "VCA sends no message of its own in this release. The table names each channel and its state.",
	"admin.notifications.channels.caption.label": "Delivery channels",
	"admin.notifications.column.channel.label":   "Channel",
	"admin.notifications.column.carries.label":   "What it carries",
	"admin.notifications.column.state.label":     "State",
	"admin.notifications.column.webhook.label":   "Webhook",
	"admin.notifications.not_built":              "Not built in this release.",
	"admin.notifications.channel.email.label":    "Email",
	"admin.notifications.channel.email.text":     "Credential offers to holders and issuance results to operators.",
	"admin.notifications.channel.sms.label":      "SMS",
	"admin.notifications.channel.sms.text":       "Credential offers to holders by phone.",
	"admin.notifications.channel.webhook.label":  "VCA webhook",
	"admin.notifications.channel.webhook.text":   "Issuance, verification and trust events to your own systems.",
	"admin.notifications.webhooks.label":         "Stack webhooks",
	"admin.notifications.webhooks.lead":          "A stack calls the webhook of a tenant on its events. The stack sends the call, not VCA.",
	"admin.notifications.webhooks.caption.label": "Stack webhooks, {1} found",
	"admin.notifications.webhooks.empty.title":   "No tenant sits on a stack with webhooks.",
	"admin.notifications.webhooks.empty.text":    "Add a tenant to such a stack on the tenants page first.",
	"admin.notifications.webhook.none.label":     "No webhook",
	"admin.notifications.webhook.unknown.label":  "Unknown now",
	"admin.notifications.webhook.on.label":       "Set",
	"admin.notifications.webhook.off.label":      "Off",
	"admin.notifications.webhook.clear.label":    "Clear",
	"admin.notifications.webhook.set.label":      "Set a webhook",
	"admin.notifications.webhook.set.text":       "The stack replaces the webhook of the tenant you choose.",
	"admin.notifications.webhook.url.label":      "Webhook URL",
	"admin.notifications.webhook.url.hint":       "An https address that your system serves. The stack calls it.",
	"admin.notifications.webhook.save.label":     "Save webhook",
	"admin.notifications.webhook.saved":          "The stack saved the webhook.",
	"admin.notifications.webhook.cleared":        "The stack removed the webhook.",

	// Admin login providers (board Admin-Providers).
	"admin.providers.lead":                    "Who signs in each role, on which stacks. VCA speaks OIDC, so the provider is yours to choose.",
	"admin.providers.add.label":               "Add provider",
	"admin.providers.new.label":               "New provider",
	"admin.providers.edit.label":              "Edit provider",
	"admin.providers.details.label":           "Provider details",
	"admin.providers.column.provider.label":   "Provider",
	"admin.providers.column.realm.label":      "Realm or issuer",
	"admin.providers.column.roles.label":      "Roles",
	"admin.providers.column.stacks.label":     "Stacks",
	"admin.providers.column.state.label":      "State",
	"admin.providers.column.default.label":    "Default",
	"admin.providers.column.actions.label":    "Actions",
	"admin.providers.caption.label":           "Login providers, {1} found",
	"admin.providers.all_stacks.label":        "All",
	"admin.providers.default.label":           "Default",
	"admin.providers.enabled.label":           "Enabled",
	"admin.providers.disabled.label":          "Disabled",
	"admin.providers.enable.label":            "Turn on",
	"admin.providers.disable.label":           "Turn off",
	"admin.providers.remove.label":            "Remove",
	"admin.providers.empty.title":             "No login provider yet.",
	"admin.providers.empty.text":              "Add the provider of the first role. The setup CLI seeds one realm per role.",
	"admin.providers.kind.label":              "Kind",
	"admin.providers.kind.hint":               "The preset fills the claim path, the scopes and the token method that you leave empty.",
	"admin.providers.display_name.label":      "Display name",
	"admin.providers.issuer.label":            "Issuer URL",
	"admin.providers.issuer.hint":             "The issuer URL or its discovery URL. Test discovery reads the metadata document.",
	"admin.providers.client.label":            "Client",
	"admin.providers.client.given.label":      "Use this client id",
	"admin.providers.client.dynamic.label":    "Register the client dynamically",
	"admin.providers.client_id.label":         "Client ID",
	"admin.providers.client_secret.label":     "Client secret reference",
	"admin.providers.client_secret.hint":      "The name of the environment variable that holds the secret. The record never holds the value.",
	"admin.providers.client_secret.kept":      "The record holds a reference. Leave the field empty to keep it.",
	"admin.providers.private_key.label":       "Private key reference",
	"admin.providers.private_key.hint":        "For private_key_jwt: the environment variable that holds the PEM key.",
	"admin.providers.token_auth.label":        "Token endpoint method",
	"admin.providers.token_auth.preset.label": "Preset default",
	"admin.providers.register.label":          "Register action",
	"admin.providers.register.auto.label":     "Let the metadata decide",
	"admin.providers.register.prompt.label":   "prompt=create",
	"admin.providers.register.keycloak.label": "Keycloak registration endpoint",
	"admin.providers.register.none.label":     "None",
	"admin.providers.roles_claim_path.label":  "Roles claim path",
	"admin.providers.roles_claim_path.hint":   "Leave the field empty for the preset value.",
	"admin.providers.roles.label":             "Applies to roles",
	"admin.providers.stacks.label":            "On stacks",
	"admin.providers.stacks.hint":             "No box means every stack.",
	"admin.providers.test.label":              "Test discovery",
	"admin.providers.save.label":              "Save provider",
	"admin.providers.discovery.label":         "Discovery result",
	"admin.providers.discovery.failed":        "Discovery failed: {1}.",
	"admin.providers.discovery.caption.label": "Provider metadata",

	// Admin trust pages (board Admin-Trust, ADR-011).
	"admin.trust.heading.label":          "Trust lists and registries",
	"admin.trust.lead":                   "A trust list names the entities this deployment accepts. A registry is where their keys and metadata resolve.",
	"admin.trust.add.label":              "Add issuer",
	"admin.trust.tabs.label":             "Trust views",
	"admin.trust.tab.list.label":         "Trust list",
	"admin.trust.tab.registries.label":   "Registries",
	"admin.trust.caption.label":          "Trust entries, {1} found",
	"admin.trust.pending_count.label":    "{1} pending review",
	"admin.trust.column.entity.label":    "Entity",
	"admin.trust.column.id.label":        "Identifier",
	"admin.trust.column.method.label":    "Method",
	"admin.trust.column.role.label":      "Role",
	"admin.trust.column.status.label":    "Status",
	"admin.trust.column.updated.label":   "Updated",
	"admin.trust.column.actions.label":   "Actions",
	"admin.trust.empty":                  "The trust list is empty. Add the first entity below.",
	"admin.trust.x509.label":             "X.509",
	"admin.trust.status.active.label":    "Trusted",
	"admin.trust.status.pending.label":   "Pending review",
	"admin.trust.status.suspended.label": "Suspended",
	"admin.trust.status.revoked.label":   "Revoked",
	"admin.trust.status.unknown.label":   "Unknown",
	"admin.trust.approve.label":          "Approve",
	"admin.trust.reject.label":           "Reject",
	"admin.trust.remove.label":           "Remove",
	"admin.trust.no_registry.label":      "No trust registry",
	"admin.trust.no_registry":            "Set VCA_ADMIN_TRUST_URL to the trust registry service. The portal edits the trust list through that service.",
	"admin.trust.new.label":              "New trust entry",
	"admin.trust.new.text":               "The registry publishes every enabled method again after the change. A pending entry stays out of the lists until you approve it.",
	"admin.trust.kind.label":             "Identifier type",
	"admin.trust.kind.did.label":         "DID",
	"admin.trust.kind.did.text":          "A decentralised identifier, for example did:web:health.go.example.",
	"admin.trust.kind.x509.label":        "X.509 subject",
	"admin.trust.kind.x509.text":         "The subject name of a certificate, as ETSI trusted lists use.",
	"admin.trust.identifier.label":       "Identifier",
	"admin.trust.identifier.hint":        "Type the DID or the subject name, for example CN=Registrar, O=Ministry of Health, C=KE.",
	"admin.trust.display_name.label":     "Display name",
	"admin.trust.role.label":             "Role",
	"admin.trust.status.label":           "Status",
	"admin.trust.endpoint.label":         "Service endpoint",
	"admin.trust.save.label":             "Save entry",
	"admin.trust.saved":                  "The registry saved the entry and publishes the lists again.",
	"admin.trust.deleted":                "The registry removed the entry from the lists.",
	"admin.trust.approved":               "The entry is active. The registry publishes it now.",
	"admin.trust.rejected":               "You rejected the request. The registry removed the entry.",

	// Admin trust registries (board Admin-Trust, registries tab, spec AD2).
	"admin.registries.add.label":                   "Add registry",
	"admin.registries.local.label":                 "Local registry",
	"admin.registries.local.published.label":       "Published",
	"admin.registries.local.text":                  "Default. It signs and publishes the lists of this deployment. Relying parties read them at these URLs.",
	"admin.registries.local.caption.label":         "Published lists",
	"admin.registries.jwks.label":                  "Signing keys",
	"admin.registries.column.list.label":           "List",
	"admin.registries.column.url.label":            "URL",
	"admin.registries.column.entries.label":        "Entries",
	"admin.registries.column.key.label":            "Key",
	"admin.registries.column.registry.label":       "Registry",
	"admin.registries.column.format.label":         "Format and anchor",
	"admin.registries.entries.label":               "{1} entries",
	"admin.registries.column.sync.label":           "Last sync",
	"admin.registries.column.state.label":          "State",
	"admin.registries.column.actions.label":        "Actions",
	"admin.registries.caption.label":               "External registries, {1} found",
	"admin.registries.state.ok.label":              "Synced",
	"admin.registries.state.error.label":           "Sync failed",
	"admin.registries.state.never.label":           "Not read yet",
	"admin.registries.never.label":                 "Never",
	"admin.registries.empty.title":                 "No external registry yet.",
	"admin.registries.empty.text":                  "Federate with a national or sector registry. VCA caches its entries for offline verification.",
	"admin.registries.sync.label":                  "Sync now",
	"admin.registries.remove.label":                "Remove",
	"admin.registries.new.label":                   "New external registry",
	"admin.registries.new.text":                    "VCA reads the list through the fetch guard and checks its signature against the anchor. Its entries stay read only here.",
	"admin.registries.name.label":                  "Name",
	"admin.registries.method.label":                "Format",
	"admin.registries.method.lote.label":           "ETSI LoTE JSON",
	"admin.registries.method.tsl.label":            "ETSI TS 119612 XML",
	"admin.registries.method.dedi.label":           "DeDi",
	"admin.registries.url.label":                   "List URL",
	"admin.registries.url.hint":                    "The URL of the signed list, or of the DeDi manifest or its root.",
	"admin.registries.anchor.label":                "Trust anchor",
	"admin.registries.anchor.jwks.label":           "JWKS URL",
	"admin.registries.anchor.jwks.text":            "A JWK Set with the keys that sign the list.",
	"admin.registries.anchor.x509.label":           "X.509 certificate",
	"admin.registries.anchor.x509.text":            "A certificate that signs the list or issued its signer. An XML list needs one.",
	"admin.registries.jwks_url.label":              "JWKS URL",
	"admin.registries.certificate.label":           "Anchor certificate",
	"admin.registries.certificate.hint":            "Paste the PEM text of the certificate.",
	"admin.registries.refresh.label":               "Refresh",
	"admin.registries.refresh.1h.label":            "Every hour",
	"admin.registries.refresh.6h.label":            "Every 6 hours",
	"admin.registries.refresh.24h.label":           "Every day",
	"admin.registries.added":                       "The registry reads the list now. The table shows the result.",
	"admin.registries.synced":                      "The registry read the list again.",
	"admin.registries.sync_failed":                 "The read failed. The registry keeps the last good copy.",
	"admin.registries.removed":                     "The registry dropped the external list and its cached entries.",
	"admin.stat.registries.external.label":         "Local and {1} external",
	"admin.providers.discovery.item.label":         "Item",
	"admin.providers.discovery.value.label":        "Value",
	"admin.providers.discovery.issuer.label":       "Issuer",
	"admin.providers.discovery.document.label":     "Discovery URL",
	"admin.providers.discovery.authorize.label":    "Authorization endpoint",
	"admin.providers.discovery.token.label":        "Token endpoint",
	"admin.providers.discovery.jwks.label":         "JWKS URI",
	"admin.providers.discovery.registration.label": "Dynamic registration",
	"admin.providers.discovery.register.label":     "Register action",
	"admin.providers.discovery.methods.label":      "Token endpoint methods",
	"admin.providers.discovery.scopes.label":       "Scopes",
	"admin.providers.discovery.yes.label":          "Supported",
	"admin.providers.discovery.no.label":           "Not offered",
	"admin.providers.push.ok":                      "{1}: the auth service took the provider.",
	"admin.providers.push.failed":                  "{1}: the push failed ({2}).",

	// Issuer portal.
	"issuer.nav.identity.label":        "Identity",
	"issuer.nav.schemas.label":         "Schemas",
	"issuer.nav.builder.label":         "Schema builder",
	"issuer.nav.issue.label":           "Issue",
	"issuer.nav.issued.label":          "Issued credentials",
	"issuer.overview.lead":             "Your issuer on {1}. Steps below unlock in order.",
	"issuer.overview.publish.label":    "Publish a schema",
	"issuer.overview.issue.label":      "Issue a credential",
	"issuer.stat.identity.label":       "Identity",
	"issuer.stat.in_registry.label":    "In trust registry",
	"issuer.stat.on_list.label":        "On trust list",
	"issuer.stat.schemas.value.label":  "{1} published",
	"issuer.stat.schemas.link.label":   "Manage schemas",
	"issuer.stat.issued.none.label":    "Nothing yet",
	"issuer.stat.issued.link.label":    "Issue the first one",
	"issuer.issue.lead":                "One credential or many, delivered the way the holder can receive it.",
	"issuer.issue.step.source.label":   "Source",
	"issuer.issue.step.claims.label":   "Claims",
	"issuer.issue.step.delivery.label": "Delivery",
	"issuer.issue.step.review.label":   "Review",
	"issuer.issue.single.label":        "Single credential",
	"issuer.issue.single.text":         "Type the claims in a form built from the schema.",
	"issuer.issue.bulk.label":          "Bulk from a source",
	"issuer.issue.bulk.text":           "CSV upload, a database query, an HTTP API or a directory. One credential per record.",
	"issuer.issue.sources.label":       "{1} sources",
	"issuer.issue.pre_auth.label":      "OID4VCI, pre-authorized code",
	"issuer.issue.pre_auth.text":       "The holder scans a QR or enters a code. No sign in at your side.",
	"issuer.issue.auth_code.label":     "OID4VCI, authorization code",
	"issuer.issue.auth_code.text":      "The holder signs in with you first, then receives the credential.",
	"issuer.issue.dc_api.label":        "Digital Credentials API",
	"issuer.issue.dc_api.text":         "Browser to wallet, on a device that supports it.",
	"issuer.issue.pdf.label":           "QR on a PDF",
	"issuer.issue.pdf.text":            "A printable document that carries the credential. For holders without a wallet.",
	"issuer.issue.hidden_note":         "This stack shows only the options it can do.",
	"issuer.issue.review.label":        "Review and issue",
	"issuer.issued.empty.title":        "Nothing issued yet.",
	"issuer.issued.empty.text":         "The first credential you issue appears here.",
	"issuer.schemas.empty.title":       "No schema yet.",
	"issuer.schemas.empty.text":        "Publish a schema from a file, or build one.",

	// Holder portal.
	"holder.nav.discover.label":      "Discover",
	"holder.nav.credentials.label":   "My credentials",
	"holder.nav.claim.label":         "Claim",
	"holder.nav.present.label":       "Present",
	"holder.overview.lead":           "Your wallet on {1}.",
	"holder.credentials.empty.title": "You hold no credential yet.",
	"holder.credentials.empty.text":  "Discover what issuers offer, or scan an offer you received.",
	"holder.discover.lead":           "What the issuers on this deployment offer.",
	"holder.claim.lead":              "Scan a QR, paste an offer link, or pick an offer from discovery.",
	"holder.present.lead":            "Answer a request with the claims it asks for.",

	// Verifier portal.
	"verifier.nav.discover.label":   "Discover",
	"verifier.nav.requests.label":   "Requests",
	"verifier.nav.dcql.label":       "DCQL builder",
	"verifier.nav.pe.label":         "Presentation Exchange",
	"verifier.nav.results.label":    "Results",
	"verifier.nav.cache.label":      "Trust cache",
	"verifier.overview.lead":        "Your verifier on {1}.",
	"verifier.requests.empty.title": "No request yet.",
	"verifier.requests.empty.text":  "Build a request, then show its QR or send its link.",
	"verifier.results.empty.title":  "No presentation yet.",
	"verifier.results.empty.text":   "Results appear here as wallets answer your requests.",
	"verifier.cache.lead":           "Trust list and registry keys, cached for offline checks within your window.",
	"verifier.cache.window.label":   "Offline window",

	// Audit reasons (ADR-039 decision 3). A reason names the cause of a
	// failure and never holds a claim value.
	"audit.reason.state":            "The sign in state was unknown or expired.",
	"audit.reason.provider":         "The login provider returned an error.",
	"audit.reason.unknown_provider": "The login provider is not registered.",
	"audit.reason.disabled":         "The login provider is off.",
	"audit.reason.role":             "The provider claims map to no role.",
	"audit.reason.nonce":            "The ID token did not match the sign in.",
	"audit.reason.upstream":         "The login provider did not answer.",
	"audit.reason.session":          "The session was not valid.",
	"audit.reason.register":         "The login provider offers no registration.",
	"audit.reason.other":            "The service could not complete the action.",
}
