// SPDX-License-Identifier: Apache-2.0

package msg

// en is the English catalogue. Keep every value inside the STE rules that
// msg_test.go checks: short sentences, active voice, approved words.
var en = map[string]string{
	// Layout and shell.
	"layout.skip.label":         "Skip to content",
	"layout.theme.label":        "Theme",
	"layout.theme.system.label": "System",
	"layout.theme.light.label":  "Light",
	"layout.theme.dark.label":   "Dark",
	"shell.main_nav.label":      "Main",
	"shell.stack_nav.label":     "Stack",
	"shell.side_nav.label":      "Portal",
	"shell.menu.label":          "Menu",
	"shell.sign_out.label":      "Sign out",
	"shell.starting.label":      "Starting",
	"shell.signed_in_as.label":  "Signed in as {1}",

	// Words that many pages share.
	"common.open.label":            "Open",
	"common.close.label":           "Close",
	"common.back.label":            "Back",
	"common.continue.label":        "Continue",
	"common.cancel.label":          "Cancel",
	"common.save.label":            "Save",
	"common.delete.label":          "Delete",
	"common.search.label":          "Search",
	"common.change.label":          "Change",
	"common.done.label":            "Done",
	"common.current.label":         "Current",
	"common.locked.label":          "Locked",
	"common.to_do.label":           "To do",
	"common.live.label":            "Live",
	"common.no_rows.label":         "No rows",
	"common.help.label":            "Help",
	"common.overview.label":        "Overview",
	"common.notifications.label":   "Notifications",
	"common.recent_activity.label": "Recent activity",
	"common.when.label":            "When",
	"common.event.label":           "Event",
	"common.detail.label":          "Detail",
	"common.status.label":          "Status",
	"common.name.label":            "Name",
	"common.version.label":         "Version",
	"common.updated.label":         "Updated {1}",
	"common.github.label":          "GitHub",
	"common.documentation.label":   "Documentation",
	"common.not_found":             "This page does not exist.",
	"common.render_failed":         "The page did not render. Try again.",
	"common.session_expired":       "Your session ended. Sign in again to continue.",

	// Roles.
	"role.admin.label":    "Admin",
	"role.issuer.label":   "Issuer",
	"role.holder.label":   "Holder",
	"role.verifier.label": "Verifier",

	// Landing page.
	"landing.title.label":             "VCA",
	"landing.hero.label":              "Verifiable Credentials Adapter",
	"landing.hero.title":              "One front door to open credential infrastructure.",
	"landing.hero.lead":               "VCA lets a government or an institution issue, hold and check digital credentials on open source stacks. One interface drives every stack.",
	"landing.hero.start.label":        "Start with VCA",
	"landing.hero.primer":             "New to credentials? Read the primer.",
	"landing.nav.how.label":           "How it works",
	"landing.nav.stacks.label":        "Stacks",
	"landing.nav.docs.label":          "Docs",
	"landing.nav.start.label":         "Start",
	"landing.how.title":               "Three ideas, two minutes.",
	"landing.how.lead":                "Enough to use VCA. Links go deeper.",
	"landing.how.dpg.label":           "A Digital Public Good",
	"landing.how.dpg.text":            "Open source software that governments can run, inspect and change. VCA drives the DPGs that issue and check credentials, so you can try each without learning each.",
	"landing.how.dpg.link.label":      "The DPG Standard",
	"landing.how.vc.label":            "A verifiable credential",
	"landing.how.vc.text":             "A digital document, like a licence or a degree, that an organisation signs and a person keeps in a wallet. Anyone who sees it can check who signed it and that nothing changed.",
	"landing.how.vc.link.label":       "W3C data model",
	"landing.how.triangle.label":      "The triangle of trust",
	"landing.how.triangle.text":       "An issuer signs, a holder keeps and presents, a verifier checks. VCA adds a trust registry and trust lists, so a verifier knows which issuers to accept.",
	"landing.how.triangle.alt":        "Issuer, holder and verifier, with the trust registry between them.",
	"landing.stacks.label":            "Stacks on this deployment",
	"landing.stacks.lead":             "Only running services appear. A role that does not run never shows as available.",
	"landing.stacks.pinned.label":     "Pinned {1}",
	"landing.stacks.components.label": "Components",
	"landing.stacks.none":             "No stack runs yet. Start a pair with the vca command, then reload this page.",
	"landing.cta.title":               "Pick a role. Walk one flow end to end.",
	"landing.cta.lead":                "Issue a credential, hold it in a wallet, check it. Each step hands you to the next.",
	"landing.cta.one_role.title":      "One role is live. Start there.",
	"landing.cta.one_role.lead":       "The role picker steps aside when one role runs.",
	"landing.footer":                  "Centre for Digital Public Infrastructure, Apache-2.0.",
	"landing.one_role.label":          "One role",
	"landing.one_role.text":           "This deployment runs the {1} role on {2}. Other roles appear when an admin deploys them.",
	"landing.one_role.continue.label": "Continue as {1}",
	"landing.none.label":              "No role yet",
	"landing.how.triangle.link.label": "Roles in the ecosystem",
	"landing.stacks.meta.label":       "VCA {1}",
	"landing.stacks.component.label":  "pinned {1}",
	"landing.stacks.roles.label":      "Roles",
	"landing.triangle.issues.label":   "issues",
	"landing.triangle.presents.label": "presents",
	"landing.triangle.trusts.label":   "trusts",
	"landing.triangle.registry.label": "Trust registry",

	// Role picker.
	"roles.title":              "How do you want to proceed?",
	"roles.lead":               "Each role has its own sign in and its own portal. You can come back and try another role at any time. The cards reflect what runs on this deployment.",
	"roles.issuer.label":       "Proceed as issuer",
	"roles.issuer.text":        "Register your organisation, define what you issue, then issue credentials one at a time or in bulk.",
	"roles.holder.label":       "Proceed as holder",
	"roles.holder.text":        "Discover what issuers offer, claim credentials into a wallet and present them when asked.",
	"roles.verifier.label":     "Proceed as verifier",
	"roles.verifier.text":      "Build a presentation request, receive a presentation, check signature, trust and status.",
	"roles.admin.label":        "Proceed as admin",
	"roles.admin.title":        "Operating this deployment?",
	"roles.admin.text":         "Manage trust lists and registries, login providers, tenants, API keys and the audit log.",
	"roles.available_on.label": "Available on {1}",
	"roles.one_role":           "This deployment runs one role, so you go straight to it.",
	"roles.other_admins.label": "Other admin portals",
	"roles.none.title":         "No role runs yet.",
	"roles.none.text":          "Start a pair with the vca command, then come back.",

	// Role intro pages.
	"intro.all_roles.label":        "All roles",
	"intro.what.label":             "What you can do",
	"intro.signin.label":           "Sign in to continue",
	"intro.signin.through":         "This deployment signs {1} in through {2}.",
	"intro.signin.realm":           "This deployment signs {1} in through {2} in the realm {3}.",
	"intro.signin.register":        "You can register if you have no account.",
	"intro.signin.lead":            "Each stack signs you in on its own pair. You can register if you have no account.",
	"intro.signin.continue.label":  "Continue to sign in",
	"intro.signin.stack.label":     "Continue on {1}",
	"intro.steps.lead":             "{1} steps on this deployment. Each one hands you to the next.",
	"intro.not_live":               "This deployment runs no {1} yet. Pick another role.",
	"intro.issuer.step3.oid4vci":   "Deliver by OID4VCI.",
	"intro.issuer.step3.pdf":       "Print a QR on a PDF for holders without a wallet.",
	"intro.verifier.step2.dcql":    "Compose a DCQL query.",
	"intro.verifier.step2.pe":      "Older wallets take a DIF Presentation Exchange query.",
	"intro.admin.trust.label":      "Set who to trust",
	"intro.admin.trust.text":       "Add issuers to the trust list. A verifier rejects unknown issuers.",
	"intro.admin.registries.label": "Connect trust registries",
	"intro.admin.registries.text":  "Publish your registry and federate with external ones.",
	"intro.admin.providers.label":  "Set up sign in",
	"intro.admin.providers.text":   "One realm per role by default. Add another OIDC provider when you need it.",
	"intro.admin.tenants.label":    "Add tenants",
	"intro.admin.tenants.text":     "Separate organisations on a stack that supports tenancy.",
	"intro.admin.keys.label":       "Keys and audit",
	"intro.admin.keys.text":        "Issue API keys for services and read the audit log.",
	"number.1.label":               "One",
	"number.2.label":               "Two",
	"number.3.label":               "Three",
	"number.4.label":               "Four",
	"number.5.label":               "Five",
	"number.6.label":               "Six",
	"intro.issuer.title":           "Issue credentials, step by step.",
	"intro.issuer.step1.label":     "Identify your organisation",
	"intro.issuer.step1.text":      "Register keys and metadata with the trust registry, in one click or with what you already have.",
	"intro.issuer.step2.label":     "Define what you issue",
	"intro.issuer.step2.text":      "Publish a schema, or build one in the schema builder. Version, extend and retire it later.",
	"intro.issuer.step3.label":     "Issue",
	"intro.issuer.step3.text":      "One credential typed by hand, or thousands from a data source.",
	"intro.issuer.step4.label":     "Manage what you issued",
	"intro.issuer.step4.text":      "Search issued credentials, review their data, suspend or revoke.",
	"intro.holder.title":           "Hold and present credentials, step by step.",
	"intro.holder.step1.label":     "Discover offers",
	"intro.holder.step1.text":      "Find what the issuers on this deployment offer.",
	"intro.holder.step2.label":     "Claim a credential",
	"intro.holder.step2.text":      "Scan a QR or follow a link. The credential lands in your wallet.",
	"intro.holder.step3.label":     "Present it",
	"intro.holder.step3.text":      "Answer a verifier's request with the claims it asks for, and nothing more.",
	"intro.holder.step4.label":     "Review what you hold",
	"intro.holder.step4.text":      "See every credential, its issuer and its status.",
	"intro.verifier.title":         "Check credentials, step by step.",
	"intro.verifier.step1.label":   "Discover schemas",
	"intro.verifier.step1.text":    "Find the credential types you can ask for.",
	"intro.verifier.step2.label":   "Build a request",
	"intro.verifier.step2.text":    "Ask for the claims you need.",
	"intro.verifier.step3.label":   "Receive a presentation",
	"intro.verifier.step3.text":    "Show a QR, paste a link or upload a document.",
	"intro.verifier.step4.label":   "Check the result",
	"intro.verifier.step4.text":    "Signature, trust and status, online or from the cache within your window.",
	"intro.admin.title":            "Run the deployment, step by step.",
	"intro.admin.step1.label":      "Sign in as admin",
	"intro.admin.step1.text":       "The first admin registers, then turns self registration off.",
	"intro.admin.step2.label":      "Set who to trust",
	"intro.admin.step2.text":       "Add issuers to the trust list and connect trust registries.",
	"intro.admin.step3.label":      "Set up sign in",
	"intro.admin.step3.text":       "One realm per role by default. Add another OIDC provider when you need it.",
	"intro.admin.step4.label":      "Manage the rest",
	"intro.admin.step4.text":       "Tenants, API keys, the audit log and notifications.",

	// Sign in chooser (ADR-035).
	"signin.title.label":               "Sign in",
	"signin.description":               "Sign in uses OpenID Connect only. VCA stores no password.",
	"signin.issuer.title":              "Sign in as an issuer.",
	"signin.holder.title":              "Sign in as a holder.",
	"signin.verifier.title":            "Sign in as a verifier.",
	"signin.admin.title":               "Sign in as an admin.",
	"signin.issuer.return":             "You return to the issuer portal after sign in.",
	"signin.holder.return":             "You return to your wallet after sign in.",
	"signin.verifier.return":           "You return to the verifier portal after sign in.",
	"signin.admin.return":              "You return to the admin portal after sign in.",
	"signin.providers.text":            "The admin sets the login providers, so a deployment can use Keycloak, WSO2 Identity Server or its own OIDC provider.",
	"signin.back.label":                "Choose another role",
	"signin.continue.label":            "Continue with",
	"signin.none":                      "This deployment has no login provider yet. Ask the admin to add one.",
	"signin.admin.none":                "This deployment has no login provider yet. Run vca admin onboard to add one.",
	"signin.register.label":            "Register a new account",
	"signin.register.with.label":       "Register with {1}",
	"signin.or.label":                  "or",
	"signin.note":                      "VCA is not tied to Keycloak. Any OIDC provider the admin adds appears here.",
	"signin.admin.callout.label":       "First admin after deployment?",
	"signin.admin.callout":             "Paste the bootstrap token, then register or sign in. Then turn off self registration in the realm settings.",
	"signin.admin.bootstrap.label":     "First super admin",
	"signin.admin.bootstrap.text":      "Paste the bootstrap token that the service printed at its first start. The token binds your identity to the super admin role once.",
	"signin.admin.provider.label":      "Provider id",
	"signin.admin.provider.hint":       "Leave the field empty when the deployment has one provider.",
	"signin.admin.token.label":         "Bootstrap token",
	"signin.admin.bind.label":          "Sign in and bind",
	"signin.admin.register_bind.label": "Register and bind",
	"role.issuer.plural.label":         "issuers",
	"role.holder.plural.label":         "holders",
	"role.verifier.plural.label":       "verifiers",
	"role.admin.plural.label":          "admins",

	// Admin portal.
	"admin.nav.trust_lists.label":       "Trust lists",
	"admin.nav.trust_registries.label":  "Trust registries",
	"admin.nav.providers.label":         "Login providers",
	"admin.nav.tenants.label":           "Tenants",
	"admin.nav.api_keys.label":          "API keys",
	"admin.nav.audit.label":             "Audit log",
	"admin.nav.console.label":           "Identity console",
	"admin.overview.lead":               "What this deployment trusts, who can sign in, and what changed.",
	"admin.stat.trust_list.value.label": "{1} trusted issuers",
	"admin.stat.trust_list.text":        "Issuers a verifier on this deployment accepts.",
	"admin.stat.registries.text":        "Add an external registry to federate.",
	"admin.stat.providers.value.label":  "{1} providers",
	"admin.stat.providers.text":         "One realm per role. Add another OIDC provider.",
	"admin.stat.tenants.value.label":    "{1} tenants",
	"admin.stat.tenants.text":           "Add tenants where a stack supports them.",
	"admin.stat.api_keys.none.label":    "No keys yet",
	"admin.stat.api_keys.text":          "Keys for services that call VCA without a user.",
	"admin.stat.audit.value.label":      "{1} events today",
	"admin.stat.audit.text":             "Sign ins, trust changes, issuance and verification.",
	"admin.checklist.title":             "First run checklist:",
	"admin.checklist.note":              "Steps stay until done.",
	"admin.checklist.register.label":    "Register the first admin",
	"admin.checklist.register.text":     "Done through the admin realm.",
	"admin.checklist.self_reg.text":     "Turn off self registration for admins.",
	"admin.checklist.self_reg.detail":   "Realm settings, Login, User registration.",
	"admin.checklist.password.text":     "Change the identity provider admin password.",
	"admin.checklist.password.detail":   "The deploy uses a default that must not stay.",
	"admin.checklist.trust.text":        "Add at least one issuer to the trust list.",
	"admin.checklist.trust.detail":      "A verifier rejects unknown issuers.",
	"admin.checklist.providers.text":    "Set the login provider for each role.",
	"admin.checklist.providers.detail":  "Defaults: one realm per role.",
	"admin.notifications.lead":          "Choose what to hear about. Delivery arrives in a later release; the settings save now.",

	// Issuer portal.
	"issuer.nav.identity.label":        "Identity",
	"issuer.nav.schemas.label":         "Schemas",
	"issuer.nav.builder.label":         "Schema builder",
	"issuer.nav.issue.label":           "Issue",
	"issuer.nav.issued.label":          "Issued credentials",
	"issuer.overview.lead":             "Your issuer on {1}. Steps below unlock in order.",
	"issuer.overview.publish.label":    "Publish a schema",
	"issuer.overview.issue.label":      "Issue a credential",
	"issuer.stat.identity.label":       "Identity",
	"issuer.stat.in_registry.label":    "In trust registry",
	"issuer.stat.on_list.label":        "On trust list",
	"issuer.stat.schemas.value.label":  "{1} published",
	"issuer.stat.schemas.link.label":   "Manage schemas",
	"issuer.stat.issued.none.label":    "Nothing yet",
	"issuer.stat.issued.link.label":    "Issue the first one",
	"issuer.issue.lead":                "One credential or many, delivered the way the holder can receive it.",
	"issuer.issue.step.source.label":   "Source",
	"issuer.issue.step.claims.label":   "Claims",
	"issuer.issue.step.delivery.label": "Delivery",
	"issuer.issue.step.review.label":   "Review",
	"issuer.issue.single.label":        "Single credential",
	"issuer.issue.single.text":         "Type the claims in a form built from the schema.",
	"issuer.issue.bulk.label":          "Bulk from a source",
	"issuer.issue.bulk.text":           "CSV upload, a database query, an HTTP API or a directory. One credential per record.",
	"issuer.issue.sources.label":       "{1} sources",
	"issuer.issue.pre_auth.label":      "OID4VCI, pre-authorized code",
	"issuer.issue.pre_auth.text":       "The holder scans a QR or enters a code. No sign in at your side.",
	"issuer.issue.auth_code.label":     "OID4VCI, authorization code",
	"issuer.issue.auth_code.text":      "The holder signs in with you first, then receives the credential.",
	"issuer.issue.dc_api.label":        "Digital Credentials API",
	"issuer.issue.dc_api.text":         "Browser to wallet, on a device that supports it.",
	"issuer.issue.pdf.label":           "QR on a PDF",
	"issuer.issue.pdf.text":            "A printable document that carries the credential. For holders without a wallet.",
	"issuer.issue.hidden_note":         "This stack shows only the options it can do.",
	"issuer.issue.review.label":        "Review and issue",
	"issuer.issued.empty.title":        "Nothing issued yet.",
	"issuer.issued.empty.text":         "The first credential you issue appears here.",
	"issuer.schemas.empty.title":       "No schema yet.",
	"issuer.schemas.empty.text":        "Publish a schema from a file, or build one.",

	// Holder portal.
	"holder.nav.discover.label":      "Discover",
	"holder.nav.credentials.label":   "My credentials",
	"holder.nav.claim.label":         "Claim",
	"holder.nav.present.label":       "Present",
	"holder.overview.lead":           "Your wallet on {1}.",
	"holder.credentials.empty.title": "You hold no credential yet.",
	"holder.credentials.empty.text":  "Discover what issuers offer, or scan an offer you received.",
	"holder.discover.lead":           "What the issuers on this deployment offer.",
	"holder.claim.lead":              "Scan a QR, paste an offer link, or pick an offer from discovery.",
	"holder.present.lead":            "Answer a request with the claims it asks for.",

	// Verifier portal.
	"verifier.nav.discover.label":   "Discover",
	"verifier.nav.requests.label":   "Requests",
	"verifier.nav.dcql.label":       "DCQL builder",
	"verifier.nav.pe.label":         "Presentation Exchange",
	"verifier.nav.results.label":    "Results",
	"verifier.nav.cache.label":      "Trust cache",
	"verifier.overview.lead":        "Your verifier on {1}.",
	"verifier.requests.empty.title": "No request yet.",
	"verifier.requests.empty.text":  "Build a request, then show its QR or send its link.",
	"verifier.results.empty.title":  "No presentation yet.",
	"verifier.results.empty.text":   "Results appear here as wallets answer your requests.",
	"verifier.cache.lead":           "Trust list and registry keys, cached for offline checks within your window.",
	"verifier.cache.window.label":   "Offline window",
}
