{{- /* SPDX-License-Identifier: Apache-2.0 */ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vca.fullname" . }}
  labels:
    {{- include "vca.labels" . | nindent 4 }}
data:
  {{ .Values.listenVariable }}: ":{{ .Values.containerPort }}"
  {{- range $name, $value := .Values.config }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
