# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: dpg-adapter-inji
description: "Verifiable Credentials Adapters: the dpg-adapter-inji service."
type: application
version: 0.1.0
appVersion: "0.1.0"
